INSERT INTO estado (id, nome, sigla) values (17, 'Tocantins', 'TO');
INSERT INTO estado (id, nome, sigla) values (11, 'Rondônia', 'RO');
INSERT INTO estado (id, nome, sigla) values (12, 'Acre', 'AC');
INSERT INTO estado (id, nome, sigla) values (13, 'Amazonas', 'AM');
INSERT INTO estado (id, nome, sigla) values (14, 'Roraima', 'RR');
INSERT INTO estado (id, nome, sigla) values (15, 'Pará', 'PA');
INSERT INTO estado (id, nome, sigla) values (16, 'Amapá', 'AP');
INSERT INTO estado (id, nome, sigla) values (21, 'Maranhão', 'MA');
INSERT INTO estado (id, nome, sigla) values (22, 'Piauí', 'PI');
INSERT INTO estado (id, nome, sigla) values (23, 'Ceará', 'CE');
INSERT INTO estado (id, nome, sigla) values (24, 'Rio Grande do Norte', 'RN');
INSERT INTO estado (id, nome, sigla) values (25, 'Paraíba', 'PB');
INSERT INTO estado (id, nome, sigla) values (27, 'Alagoas', 'AL');
INSERT INTO estado (id, nome, sigla) values (28, 'Sergipe', 'SE');
INSERT INTO estado (id, nome, sigla) values (29, 'Bahia', 'BA');
INSERT INTO estado (id, nome, sigla) values (26, 'Pernambuco', 'PE');
INSERT INTO estado (id, nome, sigla) values (31, 'Minas Gerais', 'MG');
INSERT INTO estado (id, nome, sigla) values (32, 'Espírito Santo', 'ES');
INSERT INTO estado (id, nome, sigla) values (33, 'Rio de Janeiro', 'RJ');
INSERT INTO estado (id, nome, sigla) values (35, 'São Paulo', 'SP');
INSERT INTO estado (id, nome, sigla) values (41, 'Paraná', 'PR');
INSERT INTO estado (id, nome, sigla) values (42, 'Santa Catarina', 'SC');
INSERT INTO estado (id, nome, sigla) values (43, 'Rio Grande do Sul', 'RS');
INSERT INTO estado (id, nome, sigla) values (50, 'Mato Grosso do Sul', 'MS');
INSERT INTO estado (id, nome, sigla) values (51, 'Mato Grosso', 'MT');
INSERT INTO estado (id, nome, sigla) values (52, 'Goiás', 'GO');
INSERT INTO estado (id, nome, sigla) values (53, 'Distrito Federal', 'DF');
INSERT INTO estado (id, nome, sigla) values (99, 'Exterior', 'EX');