CREATE SEQUENCE hibernate_sequence  INCREMENT 1  MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
    CACHE 1;

CREATE TABLE public.log_info
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 ),
    timestamp BIGINT,
    usuario_id bigint,
    usuario_nome varchar(100),
    ip varchar(100),
    PRIMARY KEY ( id )
);

COMMENT ON TABLE public.log_info IS 'Tabela de manutenção de Informações de LOG.';
COMMENT ON COLUMN public.log_info.timestamp IS 'Timestamp, data da alteração do log.';
COMMENT ON COLUMN public.log_info.usuario_id IS 'Identificação do usuário que fez o cadastro ou alteração.';
COMMENT ON COLUMN public.log_info.usuario_nome IS 'Identificação do usuário que fez o cadastro ou alteração.';
COMMENT ON COLUMN public.log_info.ip IS 'IP da requisição que fez o cadastro ou alteração.';

CREATE TABLE public.empresa_log
(
    id      BIGINT NOT NULL,
    REV     INTEGER NOT NULL,
    REVTYPE BIGINT,
    cnpj         character varying(14),
    razao_social  character varying(100),
    nome_fantasia character varying(100),
    data_abertura date,
    cep          character varying(8),
    logradouro   character varying(255),
    numero       character varying(20),
    complemento  character varying(255),
    bairro       character varying(120),
    municipio_id bigint,
    email        character varying(120),
    telefone     character varying(11),
    tipo_empresa  character varying(20),
    ativo boolean,
    qtd_acoes bigint,
    cotas_on bigint,
    cotas_pn bigint,
    matriz_id bigint,
    PRIMARY KEY ( id, REV )
);
COMMENT ON TABLE public.empresa_log IS 'Tabela de manutenção de LOG Empresas, holdings, Matrizes e filiais.';
COMMENT ON COLUMN public.empresa_log.id IS 'Identificação da Empresa.';
COMMENT ON COLUMN public.empresa_log.REV IS 'Identificação do log da Empresa.';
COMMENT ON COLUMN public.empresa_log.REVTYPE IS 'Identificação do tipo de alteração:
0 - INSERT
1 - UPDATE
2 - DELETE';
COMMENT ON COLUMN public.empresa_log.cnpj IS 'Número de CNPJ da Empresa cadastrada.';
COMMENT ON COLUMN public.empresa_log.razao_social IS 'Nome Empresarial da Empresa - Razão Social.';
COMMENT ON COLUMN public.empresa_log.nome_fantasia IS 'Nome Fantasia da Empresa.';
COMMENT ON COLUMN public.empresa_log.data_abertura IS 'Data de Abertura da Empresa, informação do Cartão CNPJ.';
COMMENT ON COLUMN public.empresa_log.cep IS 'Cep de indetificação do Logradouro. Informação informada no sistema e processada por webservice de cep para validação.';
COMMENT ON COLUMN public.empresa_log.logradouro IS 'Nome da Rua, avenida, etc. da empresa. Informação coletada pela Busca de CEP.';
COMMENT ON COLUMN public.empresa_log.numero IS 'Numero do endereço da empresa, caso seja sem número(S/N) deixar em branco ou zero.';
COMMENT ON COLUMN public.empresa_log.complemento IS 'Informação complementar do endereço, apto, sala, ponto de referência.';
COMMENT ON COLUMN public.empresa_log.bairro IS 'Bairro do endereço de localização.';
COMMENT ON COLUMN public.empresa_log.municipio_id IS 'Cidade de localização da empresa.';
COMMENT ON COLUMN public.empresa_log.email IS 'Email da empresa.';
COMMENT ON COLUMN public.empresa_log.telefone IS 'Número do Telefone da Empresa, podendo ser celular. Padrão 45 999999999.';
COMMENT ON COLUMN public.empresa_log.tipo_empresa IS 'Definição do tipo de empresa:
Holding
Matriz
Filial';
COMMENT ON COLUMN public.empresa_log.matriz_id IS 'Identificação da Matriz desta Empresa. Se houver.';
COMMENT ON COLUMN public.empresa_log.qtd_acoes IS 'Quantidade de Ações que esta empresa terá para divisão. Padrão para Matriz e Filiais 5.050.000';
COMMENT ON COLUMN public.empresa_log.cotas_on IS 'Percentual de cotas ON que ficarão com a empresa.';
COMMENT ON COLUMN public.empresa_log.cotas_pn IS 'Percentual de Cotas PN que ficarão com a Empresa.';
COMMENT ON COLUMN public.empresa_log.ativo IS 'Status da Empresa - T ou TRUE para ativo e F ou FALSE para inativo.';